# Generated by Django 4.1.1 on 2023-03-23 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Funcionario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(help_text="Nome do funcionario", max_length=30),
                ),
                (
                    "sobrenome",
                    models.CharField(
                        help_text="Sobrenomes do funcionario", max_length=200
                    ),
                ),
                (
                    "idade",
                    models.IntegerField(
                        help_text="Idade do funcionário (apenas numeros)"
                    ),
                ),
                ("sexo", models.CharField(help_text="Sexo: M ou F", max_length=1)),
                (
                    "empresa",
                    models.CharField(
                        help_text="Empresa que o funcionario trabalha", max_length=100
                    ),
                ),
                (
                    "departamento",
                    models.CharField(
                        help_text="Departamento que está alocado", max_length=100
                    ),
                ),
                (
                    "horas_extras",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Quantidade de horas extras",
                        max_digits=5,
                    ),
                ),
            ],
        ),
    ]
