# Generated by Django 4.1.1 on 2023-03-28 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0001_initial"),
        ("funcionarios", "0004_remove_funcionario_horas_extras"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funcionario",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="empresas.empresa",
            ),
        ),
    ]
