# Generated by Django 4.1.1 on 2023-03-24 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContabilizarHoraExtra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade_horas",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Quantidade de horas extras",
                        max_digits=5,
                    ),
                ),
            ],
        ),
    ]
